toc:
  - name: React Components
  - CistromeHGW
  - name: React Components (internal)
    children:
    - Tooltip
    - TrackColSelectionInfo
    - TrackColTools
    - TrackRowInfo
    - TrackRowLink
    - TrackWrapper
  - name: functions (internal)
    children:
    - validateWrapperOptions
    - processWrapperOptions
    - getRetinaRatio
    - setupCanvas
    - teardownCanvas
    - traverseViewConfig
    - getHMTrackIdsFromViewConfig
    - getSiblingProjectionTracksFromViewConfig
    - updateViewConfigOnSelectGenomicInterval