toc:
- name: React Components
- CistromeHGW
- name: React Components (internal)
- Tooltip
- TrackColSelectionInfo
- TrackColTools
- TrackRowInfo
- TrackControl
- TrackRowLink
- TrackWrapper
- name: Functions (internal)
- visualizationTrack
- verticalBarTrack
- dendrogramTrack
- urlTrack
- validateWrapperOptions
- processWrapperOptions
- updateRowSortOptions
- getRetinaRatio
- traverseViewConfig
- getHMTrackIdsFromViewConfig
- getSiblingVPHTrackIdsFromViewConfig
- updateViewConfigOnSelectGenomicInterval
- resolveIntervalCoordinates
- name: Classes (internal)
- Two
- TwoRectangle
- TwoCircle
- TwoLine
- TwoPath
- TwoText