toc:
- name: React Components
- CistromeHGW
- name: React Components (internal)
- CistromeHGWConsumer
- Tooltip
- ContextMenu
- TrackColSelectionInfo
- TrackColTools
- TrackRowInfoControl
- TrackRowHighlight
- TrackRowInfo
- TrackRowInfoVisNominalBar
- TrackRowInfoVisQuantitativeBar
- TrackRowInfoVisDendrogram
- TrackRowInfoVisLink
- TrackRowSearch
- SuggestionWithHighlight
- TrackWrapper
- InfoProvider
- name: Functions (internal)
- validateWrapperOptions
- processWrapperOptions
- updateWrapperOptions
- getTrackWrapperOptions
- getRetinaRatio
- traverseViewConfig
- getHMTrackIdsFromViewConfig
- getSiblingVPHTrackIdsFromViewConfig
- updateViewConfigOnSelectGenomicInterval
- updateViewConfigOnSelectRowsByTrack
- getHMSelectedRowsFromViewConfig
- getAllViewAndTrackPairs
- resolveIntervalCoordinates
- selectRows
- highlightRowsFromSearch
- insertItemToArray
- modifyItemInArray
- removeItemFromArray
- drawVisTitle
- matrixToTree
- createReducer
- name: Classes (internal)
- Two
- TwoRectangle
- TwoCircle
- TwoLine
- TwoPath
- TwoText