toc:
- name: React Components
- CistromeHGW
- name: React Components (internal)
- Tooltip
- TrackColSelectionInfo
- TrackColTools
- TrackRowInfoControl
- TrackRowHighlight
- TrackRowInfo
- TrackRowInfoVisBar
- TrackRowInfoVisDendrogram
- TrackRowInfoVisLink
- TrackWrapper
- name: Functions (internal)
- validateWrapperOptions
- processWrapperOptions
- updateRowSortOptions
- getRetinaRatio
- traverseViewConfig
- getHMTrackIdsFromViewConfig
- getSiblingVPHTrackIdsFromViewConfig
- updateViewConfigOnSelectGenomicInterval
- resolveIntervalCoordinates
- insertItemToArray
- modifyItemInArray
- removeItemFromArray
- drawVisTitle
- matrixToTree
- name: Classes (internal)
- Two
- TwoRectangle
- TwoCircle
- TwoLine
- TwoPath
- TwoText