toc:
- name: Introduction
  file: docs/Introduction.md
- name: React Components
- HiGlassMeta
- name: React Components (internal)
- HiGlassMetaConsumer
- InfoProvider
- DataTable
- CistromeToolkit
- ContextMenu
- Tooltip
- TooltipContent
- TrackRowHighlight
- TrackRowInfo
- TrackRowInfoControl
- TrackRowInfoVis
- TrackRowInfoVisDendrogram
- TrackRowInfoVisLink
- TrackRowInfoVisNominalBar
- TrackRowInfoVisQuantitativeBar
- TrackRowFilter
- TrackRowZoomOverlay
- RangeSlider
- TrackWrapper
- ViewWrapper
- ViewColumnBrush
- SuggestionWithHighlight
- name: Functions (internal)
- getConditionFromHighlightOption
- getHighlightKeyByFieldType
- addTrackWrapperOptions
- validateWrapperOptions
- processWrapperOptions
- updateWrapperOptions
- getWrapperSubOptions
- getTrackWrapperOptions
- getRetinaRatio
- traverseViewConfig
- addTrackDefToViewConfig
- getTrackDefFromViewConfig
- getHMTrackIdsFromViewConfig
- getSiblingVPHTrackIdsFromViewConfig
- updateViewConfigOnSelectGenomicInterval
- removeViewportFromViewConfig
- updateViewConfigOnSelectRowsByTrack
- getHMSelectedRowsFromViewConfig
- getUniqueViewOrTrackId
- getAllViewAndTrackPairs
- resolveIntervalCoordinates
- selectRows
- highlightRowsFromSearch
- getAggregatedRowInfo
- getAggregatedValue
- getNumOfTracks
- insertItemToArray
- modifyItemInArray
- removeItemFromArray
- drawRowHighlightRect
- drawVisTitle
- matrixToTree
- matrixToTreeWithDistance
- createReducer
- getReadableTable
- validateIntervalParams
- validateGeneParams
- makeDBToolkitIntervalAPIURL
- makeDBToolkitGeneAPIURL
- requestByInterval
- requestByGene
- componentToHex
- rgbToHex
- generateNextUniqueColor
- getRange
- wrapSvg
- name: Classes (internal)
- Two
- TwoRectangle
- TwoCircle
- TwoLine
- TwoPath
- TwoText
