toc:
- name: React Components
- CistromeHGW
- name: React Components (internal)
- CistromeHGWConsumer
- InfoProvider
- DataTable
- DataTableForIntervalTFs
- ContextMenu
- Tooltip
- TooltipContent
- TrackColSelectionInfo
- TrackColTools
- TrackRowHighlight
- TrackRowInfo
- TrackRowInfoControl
- TrackRowInfoVis
- TrackRowInfoVisDendrogram
- TrackRowInfoVisLink
- TrackRowInfoVisNominalBar
- TrackRowInfoVisQuantitativeBar
- TrackRowSearch
- TrackWrapper
- ViewWrapper
- ViewColumnBrush
- SuggestionWithHighlight
- name: Functions (internal)
- validateWrapperOptions
- processWrapperOptions
- updateWrapperOptions
- getTrackWrapperOptions
- getRetinaRatio
- traverseViewConfig
- getViewConfigOfSpecificTrack
- getHMTrackIdsFromViewConfig
- getSiblingVPHTrackIdsFromViewConfig
- updateViewConfigOnSelectGenomicInterval
- addViewConfigForNewTrack
- updateViewConfigOnSelectRowsByTrack
- getHMSelectedRowsFromViewConfig
- getUniqueViewOrTrackId
- getAllViewAndTrackPairs
- resolveIntervalCoordinates
- selectRows
- highlightRowsFromSearch
- insertItemToArray
- modifyItemInArray
- removeItemFromArray
- drawVisTitle
- matrixToTree
- createReducer
- validateIntervalParams
- makeDBToolkitIntervalAPIURL
- requestIntervalTFs
- componentToHex
- rgbToHex
- generateNextUniqueColor
- getRange
- name: Classes (internal)
- Two
- TwoRectangle
- TwoCircle
- TwoLine
- TwoPath
- TwoText