toc:
- name: React Components
- CistromeHGW
- name: React Components (internal)
- CistromeHGWConsumer
- Tooltip
- TrackColSelectionInfo
- TrackColTools
- TrackRowInfoControl
- TrackRowHighlight
- TrackRowInfo
- TrackRowInfoVisBar
- TrackRowInfoVisDendrogram
- TrackRowInfoVisLink
- TrackWrapper
- name: Functions (internal)
- validateWrapperOptions
- processWrapperOptions
- updateGlobalOptionsWithKey
- getTrackWrapperOptions
- getRetinaRatio
- traverseViewConfig
- getHMTrackIdsFromViewConfig
- getSiblingVPHTrackIdsFromViewConfig
- updateViewConfigOnSelectGenomicInterval
- updateViewConfigOnSelectRowsByTrack
- getHMSelectedRowsFromViewConfig
- resolveIntervalCoordinates
- selectRows
- highlightRowsFromSearch
- insertItemToArray
- modifyItemInArray
- removeItemFromArray
- drawVisTitle
- matrixToTree
- createReducer
- name: Classes (internal)
- Two
- TwoRectangle
- TwoCircle
- TwoLine
- TwoPath
- TwoText