toc:
- name: React Components
- CistromeHGW
- name: React Components (internal)
- Tooltip
- TrackColSelectionInfo
- TrackColTools
- TrackRowInfo
- TrackRowLink
- TrackWrapper
- name: functions (internal)
- validateWrapperOptions
- processWrapperOptions
- getRetinaRatio
- setupCanvas
- teardownCanvas
- traverseViewConfig
- getHMTrackIdsFromViewConfig
- getSiblingProjectionTracksFromViewConfig
- updateViewConfigOnSelectGenomicInterval
- resolveIntervalCoordinates