export const TRAITS = ["breast carcinoma",
    "lung adenocarcinoma, family history of lung cancer",
    "squamous cell lung carcinoma, family history of lung cancer",
    "cancer",
    "lung carcinoma, family history of lung cancer",
    "bladder carcinoma, disease progression measurement",
    "primary ovarian insufficiency",
    "colorectal cancer",
    "estrone conjugate measurement, estrone measurement",
    "androstenedione measurement, estrone measurement",
    "estrone measurement",
    "androstenedione measurement",
    "estrone conjugate measurement",
    "survival time",
    "Malignant epithelial tumor of ovary",
    "ovarian serous carcinoma",
    "pancreatic carcinoma",
    "colorectal adenocarcinoma, body mass index",
    "cervical carcinoma",
    "response to trastuzumab, cardiotoxicity",
    "peripheral neuropathy, response to taxane",
    "prostate carcinoma, breast carcinoma, ovarian carcinoma",
    "response to radiation, breast carcinoma",
    "longitudinal BMI measurement",
    "colorectal cancer, survival time",
    "metastasis measurement, colorectal cancer, survival time",
    "estrogen receptor status",
    "lung carcinoma, estrogen-receptor negative breast cancer, colorectal cancer, ovarian endometrioid carcinoma, prostate carcinoma, ovarian serous carcinoma, breast carcinoma, ovarian carcinoma, lung adenocarcinoma, squamous cell lung carcinoma",
    "lung carcinoma, estrogen-receptor negative breast cancer, colorectal cancer, ovarian endometrioid carcinoma, prostate carcinoma, ovarian serous carcinoma, breast carcinoma, ovarian carcinoma, squamous cell lung carcinoma, lung adenocarcinoma",
    "prostate carcinoma",
    "estrogen-receptor positive breast cancer",
    "estrogen-receptor negative breast cancer",
    "squamous cell carcinoma, multiple keratinocyte carcinoma susceptibility measurement, basal cell carcinoma",
    "HER2 status",
    "overall survival, pancreatic carcinoma",
    "head and neck malignant neoplasia, survival time",
    "response to radiation",
    "lung carcinoma",
    "bladder carcinoma",
    "disease recurrence, response to aromatase inhibitor",
    "differentiated thyroid carcinoma",
    "papillary thyroid carcinoma",
    "response to platinum-based neoadjuvant chemotherapy",
    "peripheral neuropathy, response to docetaxel",
    "response to trastuzumab, left ventricular diastolic function measurement, response to paclitaxel",
    "event free survival time, estrogen-receptor positive breast cancer",
    "event free survival time, estrogen-receptor positive breast cancer, response to endocrine therapy",
    "keratinocyte carcinoma",
    "colorectal cancer, alcohol consumption measurement",
    "colorectal cancer, colorectal adenoma",
    "non-small cell lung carcinoma",
    "progesterone-receptor negative breast cancer",
    "ovarian carcinoma",
    "lower urinary tract symptom, benign prostatic hyperplasia",
    "endometrial carcinoma",
    "non-melanoma skin carcinoma",
    "Hand-foot syndrome, response to fluoropyrimidines",
    "disease free survival",
    "overall survival",
    "lung carcinoma, radon exposure measurement",
    "colorectal mucinous adenocarcinoma",
    "cancer antigen 15.3 measurement",
    "cancer antigen 19.9 measurement",
    "cancer antigen 125 measurement",
    "cardiotoxicity, response to anthracycline-based chemotherapy",
    "colorectal cancer, endometrial neoplasm",
    "progression free survival, metastatic colorectal cancer, response to cetuximab, response to CAPOX-B",
    "response to radiation, obesity",
    "obesity",
    "central nervous system cancer",
    "colorectal cancer, hormone replacement therapy",
    "survival time, breast carcinoma",
    "gallbladder neoplasm",
    "testicular carcinoma",
    "event free survival time, non-small cell lung carcinoma",
    "calcium intake measurement, colorectal cancer",
    "male breast carcinoma",
    "lung carcinoma, asbestos exposure measurement",
    "total cholesterol measurement, hematocrit, stroke, ventricular rate measurement, body mass index, atrial fibrillation, high density lipoprotein cholesterol measurement, coronary artery disease, cancer, diastolic blood pressure, triglyceride measurement, systolic blood pressure, heart failure, diabetes mellitus, glucose measurement, mortality",
    "cancer, heart failure, diabetes mellitus, stroke, atrial fibrillation, mortality, coronary artery disease",
    "ovarian clear cell adenocarcinoma",
    "ovarian endometrioid carcinoma",
    "central nervous system cancer, glioma",
    "central nervous system cancer, glioblastoma multiforme",
    "thyroid carcinoma",
    "gastric carcinoma",
    "survival time, estrogen-receptor positive breast cancer, breast carcinoma, response to endocrine therapy",
    "survival time, prostate carcinoma",
    "response to bevacizumab, chemotherapy-induced hypertension",
    "cumulative dose response to bevacizumab",
    "response to platinum based chemotherapy, cytotoxicity measurement",
    "response to platinum based chemotherapy, cytotoxicity measurement, response to paclitaxel",
    "cytotoxicity measurement, response to paclitaxel",
    "response to pazopanib, serum alanine aminotransferase measurement",
    "head and neck malignant neoplasia",
    "oropharynx cancer",
    "oral cavity cancer",
    "colonic neoplasm",
    "myelosuppression, response to platinum based chemotherapy",
    "progression free survival, ovarian carcinoma, response to cisplatin, response to paclitaxel",
    "overall survival, ovarian carcinoma, response to cisplatin, response to paclitaxel",
    "response to paclitaxel",
    "response to carboplatin",
    "gastric cardia carcinoma",
    "breast cancer anti-estrogen resistance protein 3 measurement",
    "peripheral neuropathy, response to antimicrotubule agent",
    "triple-negative breast cancer",
    "esophageal carcinoma",
    "bone fracture",
    "response to cisplatin",
    "laryngeal squamous cell carcinoma, hypopharynx cancer",
    "chemotherapy-induced alopecia, response to docetaxel",
    "estrogen measurement, response to aromatase inhibitor",
    "lung carcinoma, survival time",
    "rectum cancer",
    "colon carcinoma",
    "kidney cancer",
    "amenorrhea, response to antineoplastic agent",
    "response to radiation, pain",
    "esophageal carcinoma, gastric carcinoma",
    "colorectal cancer, particulate matter air pollution measurement",
    "BRCAX breast cancer",
    "cancer aggressiveness measurement, Gleason score measurement, prostate carcinoma",
    "response to irinotecan",
    "squamous cell carcinoma, esophageal carcinoma",
    "endometrial neoplasm",
    "squamous cell carcinoma",
    "lung carcinoma, squamous cell carcinoma, gastric carcinoma",
    "cancer biomarker measurement",
    "disease free survival, breast carcinoma",
    "colorectal cancer, microsatellite instability measurement, overall survival",
    "colorectal cancer, microsatellite instability measurement",
    "disease free survival, colorectal cancer, microsatellite instability measurement",
    "colonic neoplasm, overall survival",
    "disease free survival, colonic neoplasm",
    "rectum cancer, overall survival",
    "disease free survival, rectum cancer",
    "estrogen-receptor negative breast cancer, survival time",
    "survival time, estrogen-receptor positive breast cancer",
    "smoking status measurement, lung carcinoma",
    "drug use measurement, aspirin use measurement, NSAID use measurement, colorectal cancer",
    "survival time, non-small cell lung carcinoma",
    "colorectal cancer, diet measurement",
    "response to platinum based chemotherapy",
    "breast carcinoma, hormone replacement therapy",
    "invasive lobular carcinoma, hormone replacement therapy",
    "response to radiation, prostate carcinoma, breast carcinoma",
    "response to radiation, prostate carcinoma",
    "lung adenocarcinoma",
    "response to gemcitabine",
    "small cell lung carcinoma",
    "upper aerodigestive tract neoplasm",
    "response to antineoplastic agent",
    "event free survival time, breast carcinoma",
    "response to radiation, lower urinary tract symptom",
    "skin pigmentation",
    "estradiol measurement",
    "chemotherapy-induced alopecia",
    "response to epirubicin, response to cyclophosphamide, chemotherapy-induced alopecia, response to 5' fluorouracil",
    "response to cyclophosphamide, chemotherapy-induced alopecia, response to 5' fluorouracil, response to doxorubicin",
    "chemotherapy-induced alopecia, response to paclitaxel",
    "chemotherapy-induced alopecia, response to antimicrotubule agent",
    "response to radiation, prostate carcinoma, erectile dysfunction",
    "survival time, squamous cell carcinoma, esophageal carcinoma",
    "response to radiation, Urinary retention",
    "response to radiation, Hematuria",
    "response to radiation, adverse effect",
    "response to radiation, Abnormality of the urinary system",
    "Hematochezia, response to radiation",
    "skin disease, response to cetuximab",
    "neuropathic pain",
    "response to aromatase inhibitor",
    "colorectal cancer, breast carcinoma",
    "response to tamoxifen",
    "prostate carcinoma, type II diabetes mellitus",
    "response to opioid",
    "mortality",
    "Tinnitus, response to cisplatin",
    "neutropenia, response to gemcitabine",
    "lung cancer",
    "ototoxicity, hearing loss, response to cisplatin",
    "chemotherapy-induced cytotoxicity measurement, Nausea",
    "Diarrhea, chemotherapy-induced cytotoxicity measurement",
    "sleepiness, chemotherapy-induced cytotoxicity measurement",
    "neutropenia, chemotherapy-induced cytotoxicity measurement",
    "Hand-foot syndrome, chemotherapy-induced cytotoxicity measurement",
    "non-small cell lung carcinoma, disease prognosis measurement",
    "skin disease, colon carcinoma, response to cetuximab",
    "endometrial carcinoma, endometriosis",
    "metastasis measurement, disease progression measurement",
    "metastatic colorectal cancer, survival time"]; 
